language: generic

sudo: required
services:
  - docker

before_install: 
  - gem install bundler
  - docker build -t drob/docker_projects -f Dockerfile.dev .

script:
  - docker run -e CI=true drob/docker_projects npm run test -- --coverage 