language: generic

sudo: required
services:
  - docker

before_install: 
  - docker build -t drob/docker_projects -f Dockerfile.dev 

script:
  - docker run drob/docker_projects npm test -- --coverage 